ADD_DEFINITIONS(${OSG_DEFINITIONS})

INCLUDE_DIRECTORIES(${OSG_INCLUDE_DIR})

SET(OSG_LIBRARIES
    ${OSG_LIBRARY}	
	${OSGGA_LIBRARY}
	${OGSMANIPULATOR_LIBRARY}
	${OSGDB_LIBRARY}
	${OSGUTIL_LIBRARY}
	${OSGVIEWER_LIBRARY}
	${OSGINTROSPECTION_LIBRARY}
)
